/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import naivebayes.NaiveBayes;

/**
 *
 * @author user
 */
public class Determine extends javax.swing.JPanel {
    private BufferedImage background;
    private BufferedImage dales;
    private String filename;
    /**
     * Creates new form Determine
     */
    public Determine() {
        
        try {
            background = ImageIO.read(new File("images/background.jpg"));
            dales = ImageIO.read(new File("images/daleshowresult.png"));
            
            initComponents();
        } catch (IOException ex) {
            Logger.getLogger(Determine.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void setFilename(String s) {
        this.filename = s;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        algorithmBox = new javax.swing.JComboBox();
        buyingBox = new javax.swing.JComboBox();
        maintBox = new javax.swing.JComboBox();
        doorsBox = new javax.swing.JComboBox();
        personsBox = new javax.swing.JComboBox();
        lugbootBox = new javax.swing.JComboBox();
        safetyBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        determine = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaResult = new javax.swing.JTextArea();
        backBtn = new javax.swing.JButton(new ImageIcon("images/backbutton.png"));

        jLabel1.setText("jLabel1");

        jLabel2.setText("Algorithm");

        algorithmBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Please Select Your Algorithm--", "Naive-Bayes", "k-Nearest Neighbours" }));
        algorithmBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                algorithmBoxActionPerformed(evt);
            }
        });

        buyingBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "buying","vhigh","high","med","low" }));

        maintBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "maint","vhigh","high","med","low" }));
        maintBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintBoxActionPerformed(evt);
            }
        });

        doorsBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "doors","2","3","4","5more" }));

        personsBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "persons","2","4","more" }));

        lugbootBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "lugboot","small","med","big" }));

        safetyBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "safety","high","med","low" }));

        jLabel3.setText("Buying");

        jLabel4.setText("Maint");

        jLabel5.setText("Doors");

        jLabel6.setText("Persons");

        jLabel7.setText("Lug Boot");

        jLabel8.setText("Safety");

        determine.setText("Run");
        determine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                determineActionPerformed(evt);
            }
        });

        areaResult.setColumns(20);
        areaResult.setRows(5);
        jScrollPane1.setViewportView(areaResult);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(algorithmBox, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buyingBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(maintBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(doorsBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(personsBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lugbootBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(safetyBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(determine, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(116, 116, 116))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(algorithmBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(buyingBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maintBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doorsBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(personsBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lugbootBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(safetyBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(determine)
                .addContainerGap(107, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void maintBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maintBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maintBoxActionPerformed

    private void determineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_determineActionPerformed
        System.out.println("algorithm: " + algorithmBox.getSelectedIndex());
        System.out.println("buying: " + buyingBox.getSelectedIndex());
        System.out.println("maint: " + maintBox.getSelectedIndex());
        System.out.println("doors: " + doorsBox.getSelectedIndex());
        System.out.println("persons: " + personsBox.getSelectedIndex());
        System.out.println("lug boot: " + lugbootBox.getSelectedIndex());
        System.out.println("safety: " + safetyBox.getSelectedIndex());
        String[] attBuying = { "buying","vhigh","high","med","low" };
        String[] attMaint = { "maint","vhigh","high","med","low" };
        String[] attDoors = { "doors","2","3","4","5more" };
        String[] attPersons = { "persons","2","4","more" };
        String[] attLugboot = { "lugboot","small","med","big" };
        String[] attSafety = { "safety","high","med","low" };
        String[] arrAtt = {attBuying[buyingBox.getSelectedIndex()],attMaint[maintBox.getSelectedIndex()],
            attDoors[doorsBox.getSelectedIndex()], attPersons[personsBox.getSelectedIndex()],
            attLugboot[lugbootBox.getSelectedIndex()], attSafety[safetyBox.getSelectedIndex()] };
        List<String> attInput = new ArrayList<>(Arrays.asList(arrAtt));
        areaResult.setText("Kelas dengan atribute:\n");
        areaResult.append("buying: " + buyingBox.getSelectedIndex()+"\n");
        areaResult.append("maint: " + maintBox.getSelectedIndex()+"\n");
        areaResult.append("doors: " + doorsBox.getSelectedIndex()+"\n");
        areaResult.append("persons: " + personsBox.getSelectedIndex()+"\n");
        areaResult.append("lug boot: " + lugbootBox.getSelectedIndex()+"\n");
        areaResult.append("safety: " + safetyBox.getSelectedIndex()+"\n");
        areaResult.append("File name: " + filename +"\n");
        if(algorithmBox.getSelectedIndex()==1) { //NAIVE BAYES
            NaiveBayes nb = new NaiveBayes(filename);
            areaResult.append("Kelas: " + nb.classPrediction(attInput));
        }
        else if(algorithmBox.getSelectedIndex()==2) { //KNN
            knn.Process knn = new knn.Process(filename);
            
        }
    }//GEN-LAST:event_determineActionPerformed

    private void algorithmBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_algorithmBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_algorithmBoxActionPerformed

    
    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.drawImage(background,-20,1,null);
        g.drawRect(8,8,774,539);  
        g.setColor(new Color(0,0,0));;  
        g.fillRect(8,8,774,539);
        g.drawRect(10,10,770,535);  
        g.setColor(new Color(238,221,130));;  
        g.fillRect(10,10,770,535);
        g.drawImage(dales,5,200,null);

    }
    
    public javax.swing.JButton getBackbtn() {
        return backBtn;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox algorithmBox;
    private javax.swing.JTextArea areaResult;
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox buyingBox;
    private javax.swing.JButton determine;
    private javax.swing.JComboBox doorsBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox lugbootBox;
    private javax.swing.JComboBox maintBox;
    private javax.swing.JComboBox personsBox;
    private javax.swing.JComboBox safetyBox;
    // End of variables declaration//GEN-END:variables
}
